name: Pull Request Action
 
on:
  push:
    branches:
      - dev
 
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check if PR exists
        id: check
        run: |
          prs=$(gh pr list --repo "$GITHUB_REPOSITORY" \
              --json base_ref,head_ref \
              --jq '
                  map(select(.base_ref == "qa" and .head_ref == "dev"))
                  | length
              ')
          if ((prs > 0)); then
              echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        if: steps.check.outputs.skip != 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
                title: 'Dev to QA: Auto Generated PR',
                owner,
                repo,
                head: 'dev',
                base: 'qa',
                body: [
                  'This PR is auto-generated by',
                  '[actions/github-script](https://github.com/actions/github-script).'
                ].join('\n')
            });
            await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: result.data.number,
                labels: ['feature', 'automated pr']
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}

